import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import getUser from "@/lib/utils/getUser";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import clsx from "clsx";
import Nav from "@/components/nav/nav";
import ServerProviders from "@/lib/utils/serverProviders";
import ClientProviders from "@/lib/utils/clientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: // upload,
Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ServerProviders>
        <ClientProviders>
          <body
            className={clsx(
              inter.className,
              "flex flex-col h-[100dvh] w-[100dvw] overflow-hidden"
            )}
          >
            <Nav />
            {children}
          </body>
        </ClientProviders>
      </ServerProviders>
    </html>
  );
}
